/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author nene5
 */
public class KommentarGUI extends javax.swing.JFrame {

  
    public KommentarGUI() throws InfException {
        initComponents();
        fillMyCombobox();
        fillMyTable();
    }
    
    public void fillMyCombobox() throws InfException
    {
       var getAllComments = DataBasAcess.getAllComments();
       
       for(var comment : getAllComments)
       {
           cbxKommentarer.addItem(comment);
       }
    }
       
       public void fillMyTable() 
       {
        try {
            DataBasAcess.Connect();
    
            var idQuery = "SELECT * FROM INLAGGKATEGORI";
            var results = DataBasAcess.getidb().fetchRows(idQuery);
            var inlaggKategoriList = new ArrayList<InlaggKategori>();
             
        
            for (HashMap<String, String> result : results) {

                if (result != null) {
                    
                    var id = Integer.parseInt(result.get("ID"));
                    var name = result.get("INLAGG");
                    var kategori = result.get("KATEGORI");
                    
                    var ettKlartInlagg = new InlaggKategori(id, name, kategori);
                    
                    inlaggKategoriList.add(ettKlartInlagg);
         
                }
               
                for(int i = 0 ; i < inlaggKategoriList.size(); i++)
                {
                     tblInlagg.setValueAt(inlaggKategoriList.get(i).getId(), i, 0);
                     tblInlagg.setValueAt(inlaggKategoriList.get(i).getKategori(), i, 1);
                }
                
                
            }
        } catch (InfException ex) {
            Logger.getLogger(KommentarGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        txtKommentarer = new javax.swing.JTextField();
        cbxKommentarer = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_Submit = new javax.swing.JButton();
        lblBild = new javax.swing.JLabel();
        lbltext = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInlagg = new javax.swing.JTable();

        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lägg till en kommentar");

        cbxKommentarer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKommentarerActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lagg till ett inlagg\n\n");
        jScrollPane3.setViewportView(jTextArea1);

        btn_Submit.setText("Submit");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        lblBild.setText("Bild");

        lbltext.setText("Text");

        tblInlagg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Kategori"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblInlagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInlaggMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblInlagg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKommentarer))
                            .addComponent(cbxKommentarer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Submit)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbltext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKommentarer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxKommentarer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Submit))
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxKommentarerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKommentarerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKommentarerActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        try {
            var kommentar = txtKommentarer.getText();
            var id = DataBasAcess.getMaxID();
            cbxKommentarer.addItem(kommentar);
            
            DataBasAcess.Connect();
            var kommentarQuery = "INSERT INTO KOMMENTAR (ID, NAMN) VALUES (" + String.valueOf(id) + "," + DataBasAcess.MakeDBString(kommentar) + ")";
             
            DataBasAcess.getidb().insert(kommentarQuery);
            JOptionPane.showMessageDialog(null, "Din kommentar är inlagd");
            
        } catch (InfException ex) {
            Logger.getLogger(KommentarGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
       
        
        try {
            var inlagg = jTextArea1.getText();
            var kommentar = cbxKommentarer.getSelectedItem().toString();
 
            
            DataBasAcess.Connect();
            
            var inlaggMedKategoriQuery = "INSERT INTO INLAGGKATEGORI (ID, INLAGG, KATEGORI) VALUES (" + 1 + ", '" + inlagg + "'" + "," + "'" + kommentar + "'" + ")";
            DataBasAcess.getidb().insert(inlaggMedKategoriQuery);
            
            JOptionPane.showConfirmDialog(null, "Ditt inlagg ar registrerat");
        } 
        catch (InfException ex) {
            Logger.getLogger(KommentarGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Något gick fel");
        }
        
        
        
               
           
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void tblInlaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInlaggMouseClicked
      
        try {
            var getSelectedId = tblInlagg.getSelectedRow() +1 ;
            
            DataBasAcess.Connect();
            var getInlaggQuery = "SELECT INLAGG FROM INLAGGKATEGORI WHERE ID = " + getSelectedId ;
            var result = DataBasAcess.getidb().fetchRow(getInlaggQuery);
            
            var getSelectedInlagg = result.get("INLAGG");
            
            lbltext.setText(getSelectedInlagg);
            
        } catch (InfException ex) {
            Logger.getLogger(KommentarGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
       
       
    }//GEN-LAST:event_tblInlaggMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KommentarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KommentarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KommentarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KommentarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KommentarGUI().setVisible(true);
                } catch (InfException ex) {
                    Logger.getLogger(KommentarGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cbxKommentarer;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblBild;
    private javax.swing.JLabel lbltext;
    private javax.swing.JTable tblInlagg;
    private javax.swing.JTextField txtKommentarer;
    // End of variables declaration//GEN-END:variables
}
